import json
from pathlib import Path

from airtrajectory import BuildingTopology, OpeningEdge, ToyMultizoneEnvironment, TransitionAction, ZoneNode, fork_actions


def build():
    topology = BuildingTopology.from_parts(
        [ZoneNode("living", 45), ZoneNode("bedroom", 30), ZoneNode("study", 22)],
        [
            OpeningEdge("W1", "living", "OUTSIDE", "window", 1.2),
            OpeningEdge("W2", "bedroom", "OUTSIDE", "window", 1.0),
            OpeningEdge("W3", "study", "OUTSIDE", "window", 0.9),
            OpeningEdge("D1", "living", "bedroom", "door", 1.8),
            OpeningEdge("D2", "living", "study", "door", 1.4),
        ],
    )
    env = ToyMultizoneEnvironment(topology, {"living": 1260, "bedroom": 980, "study": 840}, horizon_steps=60)
    env.reset()
    env.step([TransitionAction("D1", 100), TransitionAction("D2", 100)])
    candidates = {
        "W1 · 25%": [TransitionAction("W1", 25), TransitionAction("D1", 100), TransitionAction("D2", 100)],
        "W1 · 50%": [TransitionAction("W1", 50), TransitionAction("D1", 100), TransitionAction("D2", 100)],
        "W1 · 75%": [TransitionAction("W1", 75), TransitionAction("D1", 100), TransitionAction("D2", 100)],
        "Cross-flow · W1 + W3": [TransitionAction("W1", 50), TransitionAction("W3", 75), TransitionAction("D1", 100), TransitionAction("D2", 100)],
    }
    branches = fork_actions(env, candidates, horizon_steps=30)
    payload = {"backend": "toy-multizone-v1", "source": "generated by examples/export_web_scenarios.py", "baseline_co2": 1260, "scenarios": []}
    for name, branch in branches.items():
        last = branch.observations[-1]
        co2 = round(last["co2_ppm"]["living"])
        opens = [last["opening_pct"].get(k, 0) / 100 for k in ("W1", "W2", "W3", "D1")]
        series = [round(o["co2_ppm"]["living"]) for o in branch.observations]
        frames = [
            {
                "step": i,
                "co2": {zone: round(value) for zone, value in o["co2_ppm"].items()},
                "openings": {key: round(value, 1) for key, value in o["opening_pct"].items()},
            }
            for i, o in enumerate(branch.observations)
        ]
        payload["scenarios"].append({"name": name, "opens": opens, "co2": co2, "series": series, "frames": frames, "return": round(branch.return_value, 3)})
    Path("web/data").mkdir(parents=True, exist_ok=True)
    Path("web/data/scenarios.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


if __name__ == "__main__":
    build()
