import json
from pathlib import Path

from airtrajectory import BuildingTopology, OpeningEdge, ToyMultizoneEnvironment, TransitionAction, ZoneNode, fork_actions


def build():
    topology = BuildingTopology.from_parts(
        [ZoneNode("living", 45), ZoneNode("bedroom", 30), ZoneNode("study", 22)],
        [
            OpeningEdge("W1", "living", "OUTSIDE", "window", 1.2),
            OpeningEdge("W2", "bedroom", "OUTSIDE", "window", 1.0),
            OpeningEdge("W3", "study", "OUTSIDE", "window", 0.9),
            OpeningEdge("D1", "living", "bedroom", "door", 1.8),
            OpeningEdge("D2", "living", "study", "door", 1.4),
        ],
    )
    env = ToyMultizoneEnvironment(topology, {"living": 1260, "bedroom": 980, "study": 840}, horizon_steps=60)
    env.reset()
    env.step([TransitionAction("D1", 100), TransitionAction("D2", 100)])
    candidates = {}
    # Search-baseline candidates: intentionally simple and deterministic.
    # This is a baseline for later MPC/RL/DT comparison, not the learned policy.
    levels = (0, 25, 50, 75, 100)
    for w1 in levels:
        for w2 in levels:
            for w3 in levels:
                label = f"SEARCH · {w1}/{w2}/{w3}"
                candidates[label] = [
                    TransitionAction("W1", w1), TransitionAction("W2", w2), TransitionAction("W3", w3),
                    TransitionAction("D1", 100), TransitionAction("D2", 100),
                ]
    branches = fork_actions(env, candidates, horizon_steps=30)
    payload = {"backend": "toy-multizone-v1", "source": "generated by examples/export_web_scenarios.py", "baseline": "exhaustive-opening-search-v1", "baseline_co2": 1260, "scenarios": []}
    ranked = sorted(branches.items(), key=lambda item: item[1].return_value, reverse=True)[:4]\n    for name, branch in ranked:
        last = branch.observations[-1]
        co2 = round(last["co2_ppm"]["living"])
        opens = [last["opening_pct"].get(k, 0) / 100 for k in ("W1", "W2", "W3", "D1")]
        series = [round(o["co2_ppm"]["living"]) for o in branch.observations]
        frames = [
            {
                "step": i,
                "co2": {zone: round(value) for zone, value in o["co2_ppm"].items()},
                "openings": {key: round(value, 1) for key, value in o["opening_pct"].items()},
            }
            for i, o in enumerate(branch.observations)
        ]
        payload["scenarios"].append({"name": name, "opens": opens, "co2": co2, "series": series, "frames": frames, "return": round(branch.return_value, 3)})
    Path("web/data").mkdir(parents=True, exist_ok=True)
    Path("web/data/scenarios.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


if __name__ == "__main__":
    build()
