import json
from pathlib import Path

from airtrajectory import BuildingTopology, FastFlowField, OpeningEdge, ToyMultizoneEnvironment, TransitionAction, ZoneNode, exhaustive_opening_search, fork_window_levels


def normalized_vector(branch):
    rewards = branch.rewards
    iaq_penalty = -sum(r.iaq for r in rewards)
    wear_penalty = -sum(r.actuator_wear for r in rewards)
    final = branch.observations[-1]
    openings = final["opening_pct"]
    flow_proxy = sum(openings.get(k, 0.0) for k in ("W1", "W2", "W3")) / 3.0
    return {
        "iaq": round(max(0.0, min(100.0, 100.0 - iaq_penalty * 3.0)), 1),
        "flow": round(max(0.0, min(100.0, flow_proxy)), 1),
        "motion": round(max(0.0, min(100.0, 100.0 - wear_penalty * 25.0)), 1),
        "return": round(branch.return_value, 3),
    }


def build():
    topology = BuildingTopology.from_parts(
        [ZoneNode("living", 45), ZoneNode("bedroom", 30), ZoneNode("study", 22)],
        [
            OpeningEdge("W1", "living", "OUTSIDE", "window", 1.2),
            OpeningEdge("W2", "bedroom", "OUTSIDE", "window", 1.0),
            OpeningEdge("W3", "study", "OUTSIDE", "window", 0.9),
            OpeningEdge("D1", "living", "bedroom", "door", 1.8),
            OpeningEdge("D2", "living", "study", "door", 1.4),
        ],
    )
    env = ToyMultizoneEnvironment(topology, {"living": 1260, "bedroom": 980, "study": 840}, horizon_steps=60)
    flow = FastFlowField(topology)
    grid_points = [(x, y) for y in range(120, 541, 35) for x in range(180, 831, 35)]
    opening_xy = {"W1": (180, 210), "W2": (830, 205), "W3": (720, 540), "D1": (530, 260), "D2": (440, 370)}
    opening_area = {edge.id: edge.max_area_m2 for edge in topology.openings.values()}
    def field_for(opening_pct):
        sampled = flow.sample(grid_points, opening_pct, wind_direction_deg=240, wind_speed_mps=3.2)
        def local_speed(oid):
            ox, oy = opening_xy[oid]
            nearest = min(sampled.vectors, key=lambda v: (v.x - ox) ** 2 + (v.y - oy) ** 2)
            return (nearest.vx ** 2 + nearest.vy ** 2) ** 0.5
        flow_estimate = {oid: round(local_speed(oid) * opening_area[oid] * opening_pct.get(oid, 0.0) / 100.0, 4) for oid in opening_xy}
        return {
            "backend": sampled.backend,
            "wind_direction_deg": sampled.wind_direction_deg,
            "wind_speed_mps": sampled.wind_speed_mps,
            "grid": {"x0": 180, "y0": 120, "dx": 35, "dy": 35, "nx": 19, "ny": 13},
            "opening_flow_estimate": flow_estimate,
            "vectors": [[round(v.x, 1), round(v.y, 1), round(v.vx, 4), round(v.vy, 4)] for v in sampled.vectors],
        }
    env.reset()
    env.step([TransitionAction("D1", 100), TransitionAction("D2", 100)])
    ranked = exhaustive_opening_search(
        env,
        ("W1", "W2", "W3"),
        fixed_actions=(TransitionAction("D1", 100), TransitionAction("D2", 100)),
        levels=(0, 25, 50, 75, 100),
        horizon_steps=30,
        top_k=4,
    )
    # Canonical backend counterfactual artifact from a known post-action origin.
    tau_env = ToyMultizoneEnvironment(topology, {"living":1260,"bedroom":980,"study":840}, dt_minutes=1, horizon_steps=60)
    tau_env.reset()
    tau_env.step([TransitionAction("D1",100),TransitionAction("D2",100),TransitionAction("W1",50)])
    tau_origin=tau_env.snapshot()
    tau_branches=fork_window_levels(tau_env,"W1",horizon_steps=30)
    tau_forks={
        "origin":{"kind":"post-action-snapshot","backend":"toy-multizone-v1","state":tau_origin},
        "horizon_minutes":30,
        "branches":[{
            "label":label,
            "target_pct":branch.actions[0].target_pct,
            "end_co2_ppm":round(branch.observations[-1]["co2_ppm"]["living"]),
            "series":[round(o["co2_ppm"]["living"]) for o in branch.observations],
            "return":round(branch.return_value,3),
            "provenance":"backend-generated · toy-multizone-v1 · not engineering truth",
        } for label,branch in tau_branches.items()]
    }

    payload = {
        "schema_version": "0.3",
        "backend": "toy-multizone-v1",
        "source": "generated by examples/export_web_scenarios.py",
        "baseline": "exhaustive-opening-search-v1",
        "baseline_co2": 1260,
        "metric_provenance": {
            "co2": "backend observation",
            "return": "backend RewardVector.scalar",
            "iaq": "backend reward aggregation normalized for display",
            "motion": "backend actuator_wear aggregation normalized for display",
            "flow": "backend opening state proxy; not engineering airflow",
            "field": "FastFlowField qualitative vector grid; not CFD",
            "opening_flow_estimate": "local FastFlowField speed × opening area × opening fraction; qualitative, not calibrated m3/s",
        },
        "scenarios": [],
        "tau_forks": tau_forks,
    }
    for result in ranked:
        name, branch = result.label, result.branch
        last = branch.observations[-1]
        co2 = round(last["co2_ppm"]["living"])
        opens = [last["opening_pct"].get(k, 0) / 100 for k in ("W1", "W2", "W3", "D1")]
        series = [round(o["co2_ppm"]["living"]) for o in branch.observations]
        frames = [
            {
                "step": i,
                "co2": {zone: round(value) for zone, value in o["co2_ppm"].items()},
                "openings": {key: round(value, 1) for key, value in o["opening_pct"].items()},
                "field": field_for(o["opening_pct"]),
            }
            for i, o in enumerate(branch.observations)
        ]
        payload["scenarios"].append({
            "name": name,
            "opens": opens,
            "co2": co2,
            "series": series,
            "frames": frames,
            "return": round(branch.return_value, 3),
            "metrics": normalized_vector(branch),
        })
    Path("web/data").mkdir(parents=True, exist_ok=True)
    Path("web/data/scenarios.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


if __name__ == "__main__":
    build()
