"""Minimal CONTAM 3.4 PRJ emitter for topology/load smoke.

This is deliberately narrow:
- one level
- one contaminant
- no AHS, filters, schedules, sources/sinks, occupancy or exposures
- one power-law orifice element per opening
- named Set input controls for exterior windows; internal openings may remain fixed

The output is validated by real ContamX CI for topology loading and dynamic window control. It is still not an engineering-valid general-purpose CONTAM exporter.
"""
from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

from .contam_prj_readiness import audit_prj_readiness


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _zone_number(manifest: dict[str, Any], key: str) -> int:
    try:
        return int(manifest["zone_numbers"][key])
    except KeyError as exc:
        raise ValueError(f"missing zone number for {key}") from exc


def _path_endpoint_number(manifest: dict[str, Any], key: str) -> int:
    if key.startswith("ambient:"):
        return -1
    return _zone_number(manifest, key)


def _format_hms(total_seconds: int) -> str:
    value = int(total_seconds)
    if value <= 0:
        raise ValueError("time step must be positive")
    hours, rem = divmod(value, 3600)
    minutes, seconds = divmod(rem, 60)
    if hours > 23:
        raise ValueError("time step must be less than 24 hours")
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


def _contaminant_mode_code(mode: str) -> int:
    mapping = {"steady": 1, "transient": 2}
    try:
        return mapping[str(mode)]
    except KeyError as exc:
        raise ValueError("CONTAM contaminant mode must be steady or transient") from exc



def _dynamic_window_controls(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    paths = [
        path
        for path in manifest.get("flow_paths") or []
        if path.get("kind") == "window"
        and path.get("boundary_kind") == "exterior"
    ]
    selected = manifest.get("approved_control_opening_ids")
    if selected is not None:
        if not isinstance(selected, list) or len(selected) != len(set(selected)):
            raise ValueError("approved controls must be a unique list")
        available = {str(path["layout_opening_id"]) for path in paths}
        if set(selected) - available:
            raise ValueError("approved control not a modeled exterior window")
        paths = [path for path in paths if path["layout_opening_id"] in selected]
    paths.sort(key=lambda item: str(item["layout_opening_id"]))
    return [
        {
            "opening_id": str(path["layout_opening_id"]),
            "path_number": int(path["contam_path_number"]),
            "control_node_number": index,
            "name": str(path["layout_opening_id"]) + "_open",
            "closed_value": float(
                (path.get("airflow_element") or {}).get(
                    "closed_leakage_multiplier",
                    0.0,
                )
            ),
            "open_value": 1.0,
        }
        for index, path in enumerate(paths, start=1)
    ]


def render_minimal_prj(manifest: dict[str, Any], *, project_name: str = "airtrajectory-generated.prj") -> str:
    readiness = audit_prj_readiness(manifest)
    if not readiness["prj_serialization_ready"]:
        raise ValueError("manifest is not ready for PRJ serialization")

    if len(manifest.get("level_records") or []) != 1:
        raise ValueError("minimal PRJ emitter currently requires exactly one level")
    if len(manifest.get("contaminants") or []) != 1:
        raise ValueError("minimal PRJ emitter currently requires exactly one contaminant")

    weather = manifest["weather"]
    ta_k = float(weather["outdoor_temperature_c"]) + 273.15
    pb = float(weather["barometric_pressure_pa"])
    ws = float(weather["wind_speed_m_s"])
    wd = float(weather["wind_direction_deg"])

    contaminant = manifest["contaminants"][0]
    species = manifest["species_definitions"][0]
    project_controls = dict(manifest.get("project_controls") or {})
    simulation_mode = str(project_controls.get("mode") or "")
    sim_mf = _contaminant_mode_code(simulation_mode)
    start_time = str(project_controls.get("start") or "00:00:00")
    stop_time = str(project_controls.get("stop") or "01:00:00")
    time_step_s = int(project_controls.get("time_step_s", 60))
    time_step = _format_hms(time_step_s)
    species_name = str(species["name"]).replace(" ", "_")
    contaminant_number = int(species["contam_contaminant_number"])
    if contaminant_number != 1:
        raise ValueError("minimal PRJ emitter currently requires contaminant number 1")

    lines: list[str] = []
    emit = lines.append
    emit("ContamW 3.4.0.4 0")
    emit(project_name)
    emit("! generated by AirTrajectory minimal topology/load serializer")
    emit("! rows cols ud uf    T   uT     N     wH  u  Ao    a")
    emit(f"    58   66  0  0 {ta_k:.3f} 2    0.00 10.00 0 0.600 0.280")
    emit("!  scale     us  orgRow  orgCol  invYaxis showGeom")
    emit("  1.000e+00   0      34      27     0        1")
    emit("! Ta       Pb      Ws    Wd    rh  day u..")
    emit(f"{ta_k:.3f} {pb:.1f} {ws:.3f} {wd:.1f} 0.000 1 2 0 0 1 ! steady simulation")
    emit(f"{ta_k:.3f} {pb:.1f} {ws:.3f} {wd:.1f} 0.000 1 2 0 0 1 ! wind pressure test")
    emit("null ! no weather file")
    emit("null ! no contaminant file")
    emit("null ! no continuous values file")
    emit("null ! no discrete values file")
    emit("null ! no WPC file")
    emit("null ! no EWC file")
    emit("")
    emit("!  Xref    Yref    Zref   angle u")
    emit("   0.000   0.000   0.000   0.00 0")
    emit("! epsP epsS  tShift  dStart dEnd wp mf wpctrig")
    emit("  0.01 0.01 00:00:00   1/1   1/1  0  0  0")
    emit("! latd  longtd   tznr  altd  Tgrnd u..")
    emit("  0.00    0.00   0.00     0 283.15 2 0")
    emit("!sim_af afcalc afmaxi afrcnvg afacnvg afrelax uac Pbldg uPb")
    emit("     1      1     30   1e-05   1e-06    0.75   0 50.00   0")
    emit("!   slae rs aflmaxi aflcnvg aflinit Tadj")
    emit("      0   1    100   1e-06      1    0")
    emit("!sim_mf slae rs maxi   relcnvg   abscnvg relax gamma ucc")
    emit(f"    {sim_mf}             30  1.00e-04  1.00e-15 1.250         0 ! contaminant simulation: {simulation_mode}")
    emit("          0   1  100  1.00e-06  1.00e-15 1.100 1.000   0 ! (non-trace)")
    emit("          0   1  100  1.00e-06  1.00e-15 1.100 1.000   0 ! (trace)")
    emit("          0   1  100  1.00e-06  1.00e-15 1.100         0 ! (cvode)")
    emit("!mf_solver sim_1dz sim_1dd   celldx  sim_vjt udx")
    emit("     0        1       0     1.00e-01    0     0")
    emit("!cvode    rcnvg     acnvg    dtmax")
    emit("   0     1.00e-06  1.00e-13   0.00")
    emit("!tsdens relax tsmaxi cnvgSS densZP stackD dodMdt")
    emit("   0    0.75    20     1      0      0      0")
    emit("!date_st time_st  date_0 time_0   date_1 time_1    t_step   t_list   t_scrn")
    emit(
        f"  Jan01 {start_time}  Jan01 {start_time}  Jan01 {stop_time}  "
        f"{time_step} {time_step} 01:00:00"
    )
    emit("!restart  date  time")
    emit("    0    Jan01 00:00:00")
    emit("!list doDlg pfsave zfsave zcsave")
    emit("   0     1      1      1      1")
    emit("!vol ach -bw cbw exp -bw age -bw")
    emit("  0   1   0   0   0   0   0   0")
    emit("!rzf rzm rz1 csm srf log")
    emit("  0   0   0   1   1   1")
    emit("!bcx dcx pfq zfq zcq")
    emit("  0   0   0   0   0")
    emit("!dens   grav")
    emit(" 1.2041 9.8055")
    emit("! 0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 <- extra[]")
    emit("  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0")
    emit("0 ! rvals:")
    emit("!valZ valD valC")
    emit("   0    0    0")
    emit("!cfd   cfdcnvg  var zref maxi dtcmo solv smooth   cnvgUVW     cnvgT")
    emit("   0  1.00e-02    0    0 1000     1    1      1  1.00e-03  1.00e-03")
    emit("-999")

    emit("1 ! contaminants:")
    emit("   1")
    emit("1 ! species:")
    emit("! # s t   molwt    mdiam       edens       decay         Dm         CCdef        Cp          Kuv     u[5]      name")
    emit(f"  1 1 0 {float(species['molecular_weight_g_mol']):.4f}  0.0000e+00  0.0000e+00  0.0000e+00  1.6000e-05  0.0000e+00  1.0000e+03  0.0000e+00 11 0 0 0 0 {species_name}")
    emit("AirTrajectory generated species definition")
    emit("-999")

    level = manifest["level_records"][0]
    emit("1 ! levels plus icon data:")
    emit("! #  refHt   delHt  ni  u  name")
    emit(f"  1   {float(level['reference_height_m']):.3f}   3.000 0 0 0 <{level['name']}>")
    emit("!icn col row  #")
    emit("-999")

    for title in ("day-schedules", "week-schedules", "wind pressure profiles", "kinetic reactions", "filter elements"):
        emit(f"0 ! {title}:")
        emit("-999")
    emit("0 0 ! filters:")
    emit("-999")
    emit("0 ! source/sink elements:")
    emit("-999")

    elements = sorted(
        manifest["airflow_elements"],
        key=lambda item: int(item["contam_element_number"]),
    )
    emit(f"{len(elements)} ! flow elements:")
    for element in elements:
        nr = int(element["contam_element_number"])
        name = str(element["key"]).replace(":", "_")
        emit(f"{nr} 23 plr_orfc {name}")
        emit("AirTrajectory generated simple orifice")
        emit(
            " "
            + " ".join(
                [
                    f"{float(element['laminar_flow_coefficient']):.8g}",
                    f"{float(element['turbulent_flow_coefficient']):.8g}",
                    f"{float(element['flow_exponent']):.8g}",
                    f"{float(element['flow_area_m2']):.8g}",
                    f"{float(element['hydraulic_diameter_m']):.8g}",
                    f"{float(element['discharge_coefficient']):.8g}",
                    f"{float(element['transition_reynolds_number']):.8g}",
                    "0",
                    "0",
                ]
            )
        )
    emit("-999")
    emit("0 ! duct elements:")
    emit("-999")
    emit("0 ! control super elements:")
    emit("-999")
    dynamic_controls = _dynamic_window_controls(manifest)
    emit(f"{len(dynamic_controls)} ! control nodes:")
    emit("! # typ seq f n c1 c2 name")
    for control in dynamic_controls:
        nr = int(control["control_node_number"])
        name = control["name"]
        emit(f"{nr:4d} set {nr:3d} 0 0 0 0 {name}")
        emit(
            "AirTrajectory external opening multiplier; mechanical 0% may retain leakage floor"
        )
        emit(" 1")
    emit("-999")
    emit("0 ! simple AHS:")
    emit("-999")

    zones = sorted(
        manifest["zones"],
        key=lambda item: int(item["contam_zone_number"]),
    )
    emit(f"{len(zones)} ! zones:")
    emit("! Z#  f  s#  c#  k#  l#  relHt    Vol  T0  P0  name  clr uH uT uP uV axs cdvf")
    for zone in zones:
        nr = int(zone["contam_zone_number"])
        name = str(zone["layout_zone_id"]).replace(" ", "_")
        emit(
            f"{nr:4d}  3   0   0   0   {int(zone['level_number'])} "
            f"{float(zone['relative_height_m']):.3f} "
            f"{float(zone['volume_m3']):.6g} "
            f"{float(zone['initial_temperature_k']):.6g} "
            f"{float(zone['initial_pressure_pa']):.6g} "
            f"{name} -1 0 2 0 0 0 0 0"
        )
    emit("-999")

    emit(f"{len(zones)} ! initial zone concentrations:")
    emit(f"! Z#      {species_name}")
    initial_mf = contaminant["initial_zone_mass_fraction"]
    for zone in zones:
        emit(
            f"{int(zone['contam_zone_number']):4d} "
            f"{float(initial_mf[zone['key']]):.8e}"
        )
    emit("-999")

    paths = sorted(
        manifest["flow_paths"],
        key=lambda item: int(item["contam_path_number"]),
    )
    emit(f"{len(paths)} ! flow paths:")
    emit("! P#    f  n#  m#  e#  f#  w#  a#  s#  c#  l#    X       Y      relHt  mult wPset wPmod wazm Fahs Xmax Xmin icn dir u[4] cdvf")
    for path in paths:
        nr = int(path["contam_path_number"])
        exterior = path["boundary_kind"] == "exterior"
        flags = 1 if exterior else int(path["prj_flags"])
        n = _path_endpoint_number(manifest, path["from"])
        m = _path_endpoint_number(manifest, path["to"])
        element_number = int(path["airflow_element"]["contam_element_number"])
        control_by_opening = {
            item["opening_id"]: item["control_node_number"]
            for item in _dynamic_window_controls(manifest)
        }
        control_number = int(control_by_opening.get(path["layout_opening_id"], 0))
        emit(
            f"{nr:4d} {flags:4d} {n:4d} {m:4d} {element_number:4d} "
            f"{int(path['filter_number']):3d} {int(path['wind_profile_number']):3d} "
            f"{int(path['ahs_number']):3d} {int(path['schedule_number']):3d} {control_number:d} "
            f"{int(path['level_number']):3d} "
            f"{float(path['x_m']):.6g} {float(path['y_m']):.6g} "
            f"{float(path['relative_height_m']):.6g} "
            f"{float(path['element_multiplier']):.6g} "
            f"{float(path['constant_wind_pressure_pa']):.6g} "
            f"{float(path['wind_speed_modifier']):.6g} "
            f"{float(path['wall_azimuth_deg']):.6g} "
            f"0 0 0 23 2 -1 0 0 0 0 0 0"
        )
    emit("-999")

    for title in (
        "duct junctions",
        "initial junction concentrations",
        "duct segments",
        "source/sinks",
        "occupancy schedules",
        "exposures",
        "annotations",
    ):
        emit(f"0 ! {title}:")
        emit("-999")
    emit("* end project file.")
    return "\n".join(lines) + "\n"


def write_minimal_prj(manifest: dict[str, Any], path: str | Path) -> dict[str, Any]:
    target = Path(path)
    project_controls = dict(manifest.get("project_controls") or {})
    simulation_mode = str(project_controls.get("mode") or "")
    _contaminant_mode_code(simulation_mode)
    time_step_s = int(project_controls.get("time_step_s", 60))
    start_time = str(project_controls.get("start") or "00:00:00")
    stop_time = str(project_controls.get("stop") or "01:00:00")
    text = render_minimal_prj(manifest, project_name=target.name)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8", newline="\n")
    controls = _dynamic_window_controls(manifest)
    return {
        "path": str(target),
        "sha256": _sha256_text(text),
        "zones": len(manifest["zones"]),
        "paths": len(manifest["flow_paths"]),
        "status": "GENERATED_TOPOLOGY_LOAD_SMOKE",
        "engineering_truth": False,
        "dynamic_control_emitted": bool(controls),
        "dynamic_control_verified": False,
        "control_node_numbers": {
            item["opening_id"]: item["control_node_number"]
            for item in controls
        },
        "input_control_names": {
            item["opening_id"]: item["name"]
            for item in controls
        },
        "input_control_ranges": {
            item["opening_id"]: {
                "closed_value": item["closed_value"],
                "open_value": item["open_value"],
            }
            for item in controls
        },
        "input_control_index_policy": "runtime-discovery-by-name",
        "contaminant_simulation_mode": simulation_mode,
        "time_step_s": time_step_s,
        "simulation_start": start_time,
        "simulation_stop": stop_time,
    }
