const canvas=document.querySelector("#lab"),ctx=canvas.getContext("2d"),windEl=document.querySelector("#wind"),speedEl=document.querySelector("#speed");
const rooms=[{x:180,y:120,w:350,h:250,name:"LIVING"},{x:530,y:120,w:300,h:250,name:"BEDROOM"},{x:350,y:370,w:480,h:170,name:"STUDY"}],openings=[{id:"W1",x:180,y:210,side:"left",open:.65},{id:"W2",x:830,y:205,side:"right",open:.35},{id:"W3",x:720,y:540,side:"bottom",open:.55},{id:"D1",x:530,y:260,side:"internal",open:1}];
const fallback=[{name:"W1 · 25%",opens:[.25,.35,.55,1],co2:1045,series:[1260,1205,1162,1119,1081,1045],return:-8.2},{name:"W1 · 50%",opens:[.5,.35,.55,1],co2:925,series:[1260,1168,1090,1025,971,925],return:-7.1},{name:"W1 · 75%",opens:[.75,.35,.55,1],co2:842,series:[1260,1130,1030,952,891,842],return:-6.5},{name:"Cross-flow · W1 + W3",opens:[.55,.25,.85,1],co2:795,series:[1260,1108,1001,915,847,795],return:-6.1}];
let scenarios=fallback,baseline=1260,selected=0,cursor=0,timer=null,currentFrame=null,selectedOpening=null,objective="balanced";
async function loadScenarios(){const h=document.querySelector("#health");try{const r=await fetch("./data/scenarios.json",{cache:"no-store"});if(!r.ok)throw 0;const p=await r.json();if(!Array.isArray(p.scenarios)||p.scenarios.length<4)throw 0;scenarios=p.scenarios;baseline=p.baseline_co2;document.querySelector("#backendName").textContent=p.backend.toUpperCase();h.className="health ok";h.querySelector("b").textContent="BACKEND ARTIFACT READY"}catch(e){h.className="health fallback";h.querySelector("b").textContent="INTERACTIVE FALLBACK";document.querySelector("#backendName").textContent="FAST FALLBACK"}renderBranches();updateVector(scenarios[0])}
const particles=Array.from({length:720},(_,i)=>spawn(i));function spawn(i){const r=rooms[i%rooms.length];return{x:r.x+12+Math.random()*(r.w-24),y:r.y+12+Math.random()*(r.h-24),life:Math.random()*230,seed:Math.random()*99,px:0,py:0}}function inside(x,y){return rooms.find(r=>x>r.x&&x<r.x+r.w&&y>r.y&&y<r.y+r.h)}
function flowAt(x,y,p){const a=(+windEl.value+180)*Math.PI/180,s=+speedEl.value;let vx=Math.cos(a)*(.25+s*.13),vy=Math.sin(a)*(.25+s*.13);for(const o of openings){const dx=o.x-x,dy=o.y-y,d2=dx*dx+dy*dy+4200,k=o.open*1850/d2;vx+=dx*k;vy+=dy*k}vx+=Math.sin(y*.018+p.seed)*.12;vy+=Math.cos(x*.017-p.seed)*.1;return[vx,vy]}function reset(p){Object.assign(p,spawn(Math.floor(Math.random()*rooms.length)))}
function localFlux(o){return Math.max(0,Math.min(1,o.open*(.25+(+speedEl.value/8)*.75)))}function renderInspector(){const box=document.querySelector("#openingRows");if(!box)return;box.innerHTML=openings.map(o=>{const f=localFlux(o);return `<div class="opening-row ${selectedOpening===o.id?"active":""}" data-opening="${o.id}"><b>${o.id}</b><div class="fluxbar"><i style="width:${Math.round(f*100)}%"></i></div><strong>${Math.round(o.open*100)}%</strong></div>`}).join("");box.querySelectorAll(".opening-row").forEach(row=>row.onclick=()=>selectOpening(row.dataset.opening))}
function selectOpening(id){selectedOpening=id;document.querySelector("#selectedOpening").textContent=id+" · CLICK CANVAS TO CYCLE";renderInspector()}
function cycleOpening(id){const o=openings.find(x=>x.id===id);if(!o)return;o.open=(((Math.round(o.open*4)+1)%5)/4);renderInspector();document.querySelector("#scenario").textContent="MANUAL WHAT-IF";document.querySelector("#scenarioTitle").textContent=id+" → "+Math.round(o.open*100)+"%"}
function drawDeadZones(){for(const r of rooms){let sum=0,n=0;for(let y=r.y+24;y<r.y+r.h-16;y+=30)for(let x=r.x+24;x<r.x+r.w-16;x+=30){const q={seed:0},v=flowAt(x,y,q),s=Math.hypot(...v);sum+=s;n++;if(s<.48){ctx.strokeStyle="rgba(132,91,91,.18)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x-6,y+6);ctx.lineTo(x+6,y-6);ctx.stroke()}}}}
function drawPlan(){ctx.fillStyle="#080c0e";ctx.fillRect(0,0,1100,650);ctx.strokeStyle="#172126";ctx.lineWidth=1;for(let x=0;x<1100;x+=25){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,650);ctx.stroke()}for(let y=0;y<650;y+=25){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1100,y);ctx.stroke()}for(const r of rooms){ctx.fillStyle="#0f1619";ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle="#6f8086";ctx.lineWidth=3;ctx.strokeRect(r.x,r.y,r.w,r.h);ctx.fillStyle="#728187";ctx.font="600 11px ui-monospace";ctx.fillText(r.name,r.x+14,r.y+22)}drawDeadZones();for(const o of openings){ctx.strokeStyle=o.open>.05?"#dce7e9":"#664f4f";ctx.lineWidth=8;ctx.beginPath();if(o.side==="bottom"){ctx.moveTo(o.x-32,o.y);ctx.lineTo(o.x+32,o.y)}else{ctx.moveTo(o.x,o.y-32);ctx.lineTo(o.x,o.y+32)}ctx.stroke();ctx.fillStyle="#9aa8ad";ctx.font="9px ui-monospace";ctx.fillText(o.id+" "+Math.round(o.open*100)+"%",o.x+9,o.y-38)}}
function frame(){drawPlan();ctx.globalCompositeOperation="lighter";for(const p of particles){p.px=p.x;p.py=p.y;const[vx,vy]=flowAt(p.x,p.y,p),v=Math.hypot(vx,vy);p.x+=vx*2.1;p.y+=vy*2.1;p.life++;if(!inside(p.x,p.y)||p.life>280){reset(p);continue}ctx.strokeStyle=`rgba(160,220,230,${Math.min(.54,.08+v*.16)})`;ctx.lineWidth=.65+Math.min(1.3,v*.32);ctx.beginPath();ctx.moveTo(p.px,p.py);ctx.lineTo(p.x,p.y);ctx.stroke()}ctx.globalCompositeOperation="source-over";requestAnimationFrame(frame)}
function ensureFrames(s){if(s.frames)return s.frames;return s.series.map((v,i)=>({step:i,co2:{living:v},openings:{W1:(s.opens[0]??0)*100,W2:(s.opens[1]??0)*100,W3:(s.opens[2]??0)*100,D1:(s.opens[3]??1)*100}}))}
function metrics(s){const d=Math.max(0,baseline-s.co2);return{coverage:Math.min(96,Math.round(60+d/15)),dead:Math.max(3,Math.round(24-d/22))}}function applyFrame(i,step){selected=i;const s=scenarios[i],frames=ensureFrames(s),k=Math.max(0,Math.min(step,frames.length-1)),fr=frames[k],living=fr.co2.living??s.series[k]??s.co2,m=metrics({...s,co2:living});cursor=k;currentFrame=fr;for(const o of openings){if(fr.openings&&fr.openings[o.id]!=null)o.open=fr.openings[o.id]/100}document.querySelector("#scenario").textContent="PLAYING COUNTERFACTUAL";document.querySelector("#scenarioTitle").textContent=s.name;document.querySelector("#co2").textContent=Math.round(living).toLocaleString();document.querySelector("#coverage").textContent=m.coverage;document.querySelector("#dead").textContent=m.dead;document.querySelector("#clock").textContent=`t+${String(k+1).padStart(2,"0")}`;document.querySelector("#frameCount").textContent=`${String(k+1).padStart(2,"0")} / ${frames.length}`;const scrub=document.querySelector("#scrubber");scrub.max=Math.max(0,frames.length-1);scrub.value=k;renderInspector();document.querySelectorAll(".branch").forEach((b,j)=>b.classList.toggle("active",i===j));document.querySelectorAll(".node").forEach((n,j)=>{n.classList.toggle("cursor",j===Math.floor(k/Math.max(1,frames.length-1)*8));n.classList.toggle("past",j<=Math.floor(k/Math.max(1,frames.length-1)*8))})}
function applyScenario(i){stop();applyFrame(i,ensureFrames(scenarios[i]).length-1);updateVector(scenarios[i])}
function stop(){if(timer){clearInterval(timer);timer=null}document.querySelector("#play").textContent="▶";document.querySelector("#timeline").classList.remove("playing")}
function play(){if(timer){stop();return}const frames=ensureFrames(scenarios[selected]);if(cursor>=frames.length-1)cursor=0;document.querySelector("#play").textContent="Ⅱ";document.querySelector("#timeline").classList.add("playing");timer=setInterval(()=>{applyFrame(selected,cursor);cursor++;if(cursor>=frames.length)stop()},180)}
function scoreVector(s){const final=s.co2??baseline,iaq=Math.max(0,Math.min(100,Math.round(100-(final-420)/9))),flow=Math.round((s.opens??[]).slice(0,3).reduce((a,v)=>a+v,0)/3*100),motion=Math.max(0,100-Math.round((s.opens??[]).slice(0,3).reduce((a,v)=>a+Math.abs(v),0)/3*100));return{iaq,flow,motion,ret:s.return}}
function objectiveScore(s){const v=scoreVector(s);if(objective==="fresh")return v.iaq*.7+v.flow*.3;if(objective==="quiet")return v.iaq*.35+v.motion*.65;return v.iaq*.55+v.flow*.2+v.motion*.25}
function updateVector(s){const v=scoreVector(s);document.querySelector("#compareTitle").textContent=s.name+" · t+30";document.querySelector("#vector").innerHTML=`<span>IAQ <b>${v.iaq}</b></span><span>FLOW <b>${v.flow}</b></span><span>MOTION <b>${v.motion}</b></span><span>RETURN <b>${Number(v.ret).toFixed(2)}</b></span>`}
function spark(series){const min=Math.min(...series),max=Math.max(...series),span=Math.max(1,max-min);return series.map(v=>"▁▂▃▄▅▆▇█"[Math.min(7,Math.floor((v-min)/span*7))]).join("")}function renderBranches(){const best=scenarios.reduce((b,s,i,a)=>objectiveScore(s)>objectiveScore(a[b])?i:b,0);document.querySelector("#branches").innerHTML=scenarios.map((s,i)=>`<article class="branch ${i===best?"best":""}" data-i="${i}"><b>${s.name}</b><div class="outcome">${s.co2} ppm</div><span class="delta">↓ ${baseline-s.co2} ppm · t+30</span><div class="spark">${spark(s.series)}</div><small>return ${s.return}</small></article>`).join("");document.querySelectorAll(".branch").forEach(b=>b.onclick=()=>{const i=+b.dataset.i;applyScenario(i);updateVector(scenarios[i])})}
document.querySelector("#fork").onclick=()=>{renderBranches();stop();applyFrame(2,0)};document.querySelector("#strategy").onclick=()=>{renderBranches();const best=scenarios.reduce((b,s,i,a)=>objectiveScore(s)>objectiveScore(a[b])?i:b,0);stop();applyFrame(best,0);updateVector(scenarios[best]);play()};document.querySelector("#play").onclick=play;document.querySelector("#scrubber").oninput=e=>{stop();applyFrame(selected,+e.target.value)};windEl.oninput=()=>document.querySelector("#windLabel").textContent=`${windEl.value}°`;speedEl.oninput=()=>{document.querySelector("#speedLabel").textContent=`${(+speedEl.value).toFixed(1)} m/s`;renderInspector()};const tl=document.querySelector("#timeline");for(let i=0;i<9;i++){const n=document.createElement("div");n.className="node"+(i===5?" active":"");tl.append(n);if(i<8){const l=document.createElement("div");l.className="line";tl.append(l)}}loadScenarios();frame();
canvas.addEventListener("mousemove",e=>{const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*canvas.width/rect.width,y=(e.clientY-rect.top)*canvas.height/rect.height,r=inside(x,y),p=document.querySelector("#probe");if(!r){p.classList.add("hidden");return}const key=r.name.toLowerCase(),co2=currentFrame?.co2?.[key],v=flowAt(x,y,{seed:0}),speed=Math.hypot(...v);p.classList.remove("hidden");p.style.left=Math.min(rect.width-155,e.clientX-rect.left+14)+"px";p.style.top=Math.max(55,e.clientY-rect.top-18)+"px";document.querySelector("#probeRoom").textContent=r.name;document.querySelector("#probeValue").textContent=(co2!=null?co2+" ppm · ":"")+speed.toFixed(2)+" flow proxy"});canvas.addEventListener("mouseleave",()=>document.querySelector("#probe").classList.add("hidden"));renderInspector();
document.querySelectorAll(".preset").forEach(btn=>btn.onclick=()=>{objective=btn.dataset.preset;document.querySelectorAll(".preset").forEach(x=>x.classList.toggle("active",x===btn));renderBranches()});
canvas.addEventListener("click",e=>{const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*canvas.width/rect.width,y=(e.clientY-rect.top)*canvas.height/rect.height;let hit=null,dist=Infinity;for(const o of openings){const d=Math.hypot(o.x-x,o.y-y);if(d<dist&&d<55){hit=o;dist=d}}if(hit){selectOpening(hit.id);cycleOpening(hit.id)}});